name: state-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changed_states:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"
      - id: filter
        run: |
          echo "filtered_files=$(jq -rMc '[.[] | select(. | contains(".sls")) | select(. | contains("init") | not) | sub("/"; "."; "g") | sub(".sls"; ""; "g")]' <<< '${{ steps.files.outputs.added_modified }}')" > $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.filter.outputs.filtered_files }}

  test_states:
    needs: changed_states
    runs-on: ubuntu-latest
    if: ${{ needs.changed_states.outputs.matrix != '[]' }}
    strategy:
      matrix:
        salt: [3006]
        os: [20.04, 22.04, 24.04]
        state: ${{ fromJson(needs.changed_states.outputs.matrix) }}
        include:
          - os: 20.04
            code: focal
          - os: 22.04
            code: jammy
          - os: 24.04
            code: noble
    container:
      image: docker://ghcr.io/ekristen/cast-tools/saltstack-tester:${{ matrix.code }}-${{ matrix.salt }}
    steps:
      - uses: actions/checkout@v4
      - name: test-state
        run: |
          salt-call -l info --file-root . --local --retcode-passthrough --state-output=mixed state.sls ${{ matrix.state }} pillar="{bitcurator_user: root}"
